return {
  "mfussenegger/nvim-lint",
  event = "LazyFile",
  opts = {
    -- Event to trigger linters
    events = { "BufWritePost", "BufReadPost", "InsertLeave" },
    linters_by_ft = {
      fish = { "fish" },
      bash = { "bash" },
      python = { "ruff" },
      jsx = { "biomejs" },
      css = { "biomejs" },
      raphql = { "biomejs" },
      javascript = { "eslint_d" },
      typescript = { "eslint_d" },
      make = { "mbake" },
      c = { "clangtidy", "cppcheck", "cpplint" },
      cpp = { "clangtidy", "cppcheck", "cpplint" },
      rust = { "clippy" },
      cmake = { "cmake_lint" },
      gitcommit = { "commitlint" },
      go = { "golangcilint" },
      dockerfile = { "hadolint" },
      html = { "htmlhint", "tidy" },
      json = { "json5" },
      kotlin = { "ktlint" },
      latex = { "lacheck" },
      lua = { "luac", "luacheck" },
      markdown = { "mado" },
      php = { "mago_lint", "mago_analyze" },
      matlab = { "mh_lint" },
      nix = { "nix" },
      ruby = { "ruby" },
      sql = { "sqlfluff" },
      swift = { "swiftlint" },
      zsh = { "zsh" },
    },
  },
}
